ActiveLAMP\Bundle\TaxonomyBundle\Entity\EntityTerm:
    type: entity
    table: taxonomy_entity_term
    repositoryClass: ActiveLAMP\Taxonomy\Doctrine\ORM\EntityTermRepository
    fields:
        id:
            type: integer
            unique: true
            nullable: false
            id: true
            generator:
                strategy: IDENTITY

        entityType:
            type: string
            length: 255
            unique: false
            nullable: false
            column: entity_type

        entityIdentifier:
            type: integer
            unique: false
            nullable: false
            column: entity_id

    manyToOne:
        term:
            targetEntity: ActiveLAMP\Taxonomy\Entity\TermInterface
            inversedBy: entityTerms
            joinColumns:
                term_id:
                    referencedColumnName: id
            orphanRemoval: false
